version: '3.8'

services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: greenforecast-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres.qunzkuxuduqmqyjvtuqf:A07180295e%40%40@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
      - OPEN_METEO_BASE_URL=https://api.open-meteo.com/v1
      - CORS_ORIGINS=["http://localhost:3000", "http://frontend:3000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data/uploads:/app/data/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greenforecast-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"

